### ISSUE TITLE
SBUS output

### ISSUE THREAD

**Issue by sk8board** [CapnBry/CRServoF#22]
Many fixed wing flight controllers require SBUS as an input. Can you add a change to output SBUS?

Thank you for your work on an ELRS converter.

**Comment by CapnBry** [comment]
Why would this output SBUS? This is for outputting PWM, not digital.

**Comment by sk8board** [comment]
Because my fixed wing flight controllers require SBUS input, I have to use an ELRS receiver connected to a Matek converter (CRSF to PWM) then use another converter (PWM to SBUS) so I can use ERLS with fixed wing flight controllers.

If your software would convert from CRSF to SBUS, then I could eliminate the PWM to SBUS converter board. Why not go one step further to include SBUS on another pin?

**Comment by CapnBry** [comment]
Because SBUS requires inverters and the STM32F103 does not have built in inverters, requiring an external inverter. Matek makes CRSF to SBUS boards now too (or they will very soon as I have seen them in the wild) if you need SBUS support.

Yes, I could make code to output SBUS and then provide a schematic showing how to add more hardware to invert it, but I really do not have the time to waste on something I would never use, when there are so many more cool things to work on that I will use. It isn't just writing the code and drawing schematics, there's additional support time required to help people with it too that would also fall on my shoulders.

**Comment by sk8board** [comment]
Thank you for your help. I will wait for the Matek converter.
